README.md: guessinggame.sh
	@echo "# Guessing Game" > README.md
	@echo "" >> README.md
	@echo "This file was generated by running \`make run\` on:" >> README.md
	@date >> README.md
	@echo "" >> README.md
	@echo "The number of lines of code in guessinggame.sh is:" >> README.md
	@wc -l < guessinggame.sh >> README.md
	@echo "" >> README.md
	@echo "Run the game with:" >> README.md
	@echo "\`\`\`bash" >> README.md
	@echo "bash guessinggame.sh" >> README.md
	@echo "\`\`\`" >> README.md
	@echo "To remove the README.md file and startover fresh"
	@echo "\`\`\`" >> README.md
	@echo "make clean >> README.md
	@echo "\`\`\`" >> README.md

run: guessinggame.sh README.md
	@chmod +x guessinggame.sh
	@bash guessinggame.sh

clean: README.md
	@rm -f README.md